# Register t3footnotes plugin for CKEditor 5
editor:
  config:
    importModules:
      - { module: "@cag/t3footnotes", exports: [ "T3Footnotes" ] }

# Allow the necessary tags in processing
processing:
  allowTags:
    - sup
    - a
    - span
  allowAttributes:
    - class
    - id
    - href
    - title
    - style
